### ISSUE TITLE
服务不稳定，不定时遇到500返回码

### ISSUE THREAD

**Issue by Xunflash** [ShilongLee/Crawler#31]
服务不太稳定，不定时遇到500返回码，看起来是请求超时导致的，能否优化一下超时处理逻辑呢
```
INFO:     127.0.0.1:42492 - "GET /xhs/detail?id=658833e1000000000602a2cc HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/xunflash/Crawler/service/xhs/views/detail.py", line 19, in detail
    res, succ = await request_detail(id, account.get('cookie', ''))
  File "/home/xunflash/Crawler/service/xhs/logic/detail.py", line 16, in request_detail
    resp = await requests.get(url, headers=headers)
  File "/home/xunflash/Crawler/lib/requests/requests.py", line 14, in get
    response = await client.get(url, headers=headers, params=params)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/xunflash/Crawler/.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
```

**Comment by ShilongLee** [comment]
可以考虑控制一下频率

**Comment by NanmiCoder** [comment]
这个问题我今天在RP代码前跑xhs单测时也发现这个同样的问题了，同样的代码，有时会有一个case跑失败的情况。

我们是不是可以加一个重试解决这种网络不问题的问题。例如使用 [tenacity](https://github.com/jd/tenacity)

```python
from tenacity import RetryError, retry, stop_after_attempt, wait_fixed

@retry(stop=stop_after_attempt(3), wait=wait_fixed(1))
async def get(url, headers=None, params=None) -> Response:
    async with httpx.AsyncClient() as client:
        response = await client.get(url, headers=headers, params=params)
        return Response(response.status_code, response.text)
```

**Comment by ShilongLee** [comment]
> 这个问题我今天在RP代码前跑xhs单测时也发现这个同样的问题了，同样的代码，有时会有一个case跑失败的情况。
> 
> 我们是不是可以加一个重试解决这种网络不问题的问题。例如使用 [tenacity](https://github.com/jd/tenacity)
> 
> ```python
> from tenacity import RetryError, retry, stop_after_attempt, wait_fixed
> 
> @retry(stop=stop_after_attempt(3), wait=wait_fixed(1))
> async def get(url, headers=None, params=None) -> Response:
>     async with httpx.AsyncClient() as client:
>         response = await client.get(url, headers=headers, params=params)
>         return Response(response.status_code, response.text)
> ```

这确实是一个好办法

**Comment by ShilongLee** [comment]
> 这个问题我今天在RP代码前跑xhs单测时也发现这个同样的问题了，同样的代码，有时会有一个case跑失败的情况。
> 
> 我们是不是可以加一个重试解决这种网络不稳定的问题。例如使用 [tenacity](https://github.com/jd/tenacity)
> 
> ```python
> from tenacity import RetryError, retry, stop_after_attempt, wait_fixed
> 
> @retry(stop=stop_after_attempt(3), wait=wait_fixed(1))
> async def get(url, headers=None, params=None) -> Response:
>     async with httpx.AsyncClient() as client:
>         response = await client.get(url, headers=headers, params=params)
>         return Response(response.status_code, response.text)
> ```

已增加重试 `https://github.com/ShilongLee/Crawler/commit/17152676b038bb18044f366eefef7cdf1bd5f8dd`
