### ISSUE TITLE
failed to install on windows platform

### ISSUE THREAD

**Issue by wnpllrzodiac** [ShilongLee/Crawler#68]
```
Collecting uvloop==0.19.0
  Downloading uvloop-0.19.0.tar.gz (2.3 MB)
     ---------------------------------------- 2.3/2.3 MB 18.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "D:\git\Crawler\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "D:\git\Crawler\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\git\Crawler\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Mag\AppData\Local\Temp\pip-build-env-jkxfij5u\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Mag\AppData\Local\Temp\pip-build-env-jkxfij5u\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
          self.run_setup()
        File "C:\Users\Mag\AppData\Local\Temp\pip-build-env-jkxfij5u\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
```

**Comment by ShilongLee** [comment]
用的是什么命令

**Comment by wnpllrzodiac** [comment]
pip3 install -r requirements.txt

换成 pip3 install -r requirements-windows.txt
就可以了。
